ghc-options: -Wall

ghc-prof-options: -fprof-auto -prof

dependencies:
  - base >= 4.8.1
  - bytestring
  - cassava
  - text
  - hyperloglog
  - approximate

executables:
  stats:
    main: Main.hs
    source-dirs:
      - driver
      - src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - src
      - test
    dependencies:
      - hspec
      - QuickCheck
